---
# tasks file for win_ad_install
- name: install AD-Domain-Services feature
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: AD_Feature_change

- name: Setup AD
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ansible_password}}"
  when: AD_Feature_change.changed == true
  register: ad_setup_status

- name: Reboot Win Server post AD install
  win_reboot:
  when: ad_setup_status.reboot_required is defined

- name: Print AD Domain List
#  win_shell: GET-ADDomain -Identity "{{ad_domain_name}}"
  win_shell: 'nltest /dclist:"{{ ad_domain_name }}"'
  register: dc_list

- name: installation status
  debug:
    msg: "Domain Controller Installed"
  when: ad_domain_name in dc_list.stdout
